# Vanya Kootchin
# January 11th, 2022

"""Library for reading PDFs into python data structures

   Requires 'pdfplumber' library...
   
        - pip install pdfplumber
        
    ...for whichever virtual environment you're using

"""

import sys    

try: # pdfplumber
  import pdfplumber
except:
  print('Error:\tpdfplumber library has not been installed.\n\tTry \'pip install pdfplumber\' in venv.')
  sys.exit(0)

def readPDF(fp):
    """A function for reading a given pdf and returning the pages 
    as a list of strings in python

    Args:
        fp (string): The path to the PDF intended for reading
        
    Returns:
        JSON obj: A pairing of page number key values in the form
              {
                "0": "The contents on the first page",
                "1": "The contents on the second page",
                "2": "The contents on the third page"
              }
    """
    pages = {}
    i = 0
    with pdfplumber.open(fp) as pdf:
        for page in pdf.pages:
            pages[i] = page.extract_text()
            i = i + 1
    return pages
  
  

def printPDF(pdfObj):
      """A function for printing a PDF object generated by 'readPDF'

      Args:
          pdfObj (dict.): A PDF object generated by 'readPDF' in the form:
            {
                "0": "The contents on the first page",
                "1": "The contents ... etc., 
      """
      for pageNum in pdfObj:
            print(f'\n[Page {pageNum}]\n')
            splitPage = pdfObj[pageNum].split('\n')
            for line in splitPage:
                  print('-\t', line)

